version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      #- aws ecr get-login --no-include-email --region us-east-1
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 678878256416.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      #- echo Build started on `date`
      #- echo Building Docker test image...
      #- docker build -t $IMAGE_REPO_NAME:$TEST_IMAGE_TAG -f Dockerfile.dev .
      #- docker run -e CI=true $IMAGE_REPO_NAME:$TEST_IMAGE_TAG npm run test
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t cicd-yasir:aws .
      - docker tag cicd-yasir:aws 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:aws
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image... 
      - docker push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:aws