# Change the following to your desired values:
#   __ACCOUNT_NUMBER__
#   __ECR_REGION__
#   __ECR_REPOSITORY_NAME__
#   __ECS_CONTAINER_NAME__

version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
  commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:v2.0 .
      #- docker tag cicd-yasir:v1.0 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:v1.0      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:v2.0
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json