# Change the following to your desired values:
#   __ACCOUNT_NUMBER__
#   __ECR_REGION__
#   __ECR_REPOSITORY_NAME__
#   __ECS_CONTAINER_NAME__

version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      #- echo Build started on `date`
      #- echo Building Docker test image...
      #- docker build -t $IMAGE_REPO_NAME:$TEST_IMAGE_TAG -f Dockerfile.dev .
      #- docker run -e CI=true $IMAGE_REPO_NAME:$TEST_IMAGE_TAG npm run test
      - echo Build started on `date`
      - echo Building the Docker image...
       #- docker build 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir .
       - docker build -t 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest .
       - docker tag 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image... 
      #- docker push cicd-yasir/awscodebuild
      #- docker push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir
      - docker push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest
      - docker push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest
artifacts:
  files: imagedefinitions.json