# Change the following to your desired values:
#   __ACCOUNT_NUMBER__
#   __ECR_REGION__
#   __ECR_REPOSITORY_NAME__
#   __ECS_CONTAINER_NAME__

version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest .
      - docker tag push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest
      - docker push 678878256416.dkr.ecr.us-east-1.amazonaws.com/cicd-yasir:latest
      #- echo Writing image definitions file...
      #- printf '[{"name”:"__ECS_CONTAINER_NAME__","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json