apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api-v1
  version: v1
  namespace: default
  
spec:
  
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: hello-world-rest-api
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
     
      labels:
        app: hello-world-rest-api
        version: v1
    spec:
      containers:
      - name: hello-world-rest-api
        image: in28min/hello-world-rest-api:0.0.1.RELEASE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

      restartPolicy: Always
     
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
 
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default

spec:

  ports:
  - name: helloworld
    nodePort: 30510
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: nginx
    nodePort: 30410
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer